


notarget:
	@echo 'specify one of the following targets:'
	@echo '		alphasc'
	@echo '		linux'
	@echo '		origin'

alphasc:
	make -f makefile.AlphaSC

linux:
	make -f makefile.i686

origin:
	make -f makefile.sgi4d


clean: 
	rm -f *.o
