      SUBROUTINE DERIV (TRACCIA_LETTA,TRACCIA_TEMP,NCAMP,DT)
      
      IMPLICIT NONE
      
      INTEGER*4 NCAMP
      REAL*4    DT
      REAL*4    TRACCIA_LETTA(NCAMP), TRACCIA_TEMP(NCAMP)
      
      INTEGER*4 I
                      
           TRACCIA_TEMP(1)=(TRACCIA_LETTA(2)-TRACCIA_LETTA(1))/DT
           DO 666 I=2,NCAMP-1
               TRACCIA_TEMP(I)=(TRACCIA_LETTA(I+1)-TRACCIA_LETTA(I-1))/(2.0*DT)
 666       CONTINUE
           TRACCIA_TEMP(NCAMP)=(TRACCIA_LETTA(NCAMP)-TRACCIA_LETTA(NCAMP-1))/DT
        
      END   